SELECT ID,
       TENANT__R__EXTERNAL_ID__C,
       CREATED,
       CREATED_BY_ID,
       LAST_MODIFIED,
       LAST_MODIFIED_BY_ID,
       GIFT_CARD_ID,
       REQUEST_SOURCE_ID,
       TRANSACTION_TYPE_ID,
       AMOUNT_IN_CENTS,
       USER_ID,
       COMMENT
FROM {{source('GENERAL','GIFT_CARD_TRANSACTION')}}