SELECT ID,
       TENANT__R__EXTERNAL_ID__C,
       CREATED,
       CREATED_BY_ID,
       LAST_MODIFIED,
       LAST_MODIFIED_BY_ID,
       GIFT_CARD_TRANSACTION_ID,
       INVOICE_ID,
       REDEEMED_BY_USER_ID,
       INVOICE_LINE_ITEM_ID,
       REFUND
FROM {{source('GENERAL','GIFT_CARD_TRANSACTION_INVOICE')}}